apiVersion: v1
kind: Service
metadata:
  name: demoapi-service
  namespace: demo
spec:
  type: NodePort
  selector:
    app: demoapi
  ports:
    - name: rest-api
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
