apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: demo
spec:
  selector:
    app: kafka
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: kafka-controller
      protocol: TCP
      port: 9093
      targetPort: 9093