apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: demoapi-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: demoapi-repo-image
  policy:
    semver:
      range: 0.0.x