---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demoapi-repo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: demoapi-repo
  targetNamespace: demo
  timeout: 1m0s
  wait: true
